spring:
  redis:
    port:  6379
    host:  192.168.159.100
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 1
    connect-timeout:   1000
    password: lmy2003.